@SuperHeroAPI-DotNet8_HostAddress = https://localhost:7208
@SuperHeroAPI_DotNet8_HostAddress = http://localhost:5070

GET {{SuperHeroAPI-DotNet8_HostAddress}}/api/superhero

###

GET {{SuperHeroAPI-DotNet8_HostAddress}}/api/superhero/0

###

POST {{SuperHeroAPI-DotNet8_HostAddress}}/api/superhero
Content-Type: application/json

{
  //SuperHero
}

###


PUT {{SuperHeroAPI-DotNet8_HostAddress}}/api/superhero
Content-Type: application/json

{
  //SuperHero
}

###

DELETE {{SuperHeroAPI-DotNet8_HostAddress}}/api/superhero?id=0

###